### PR TITLE
Fixed the exceptional items bug

### PR DESCRIPTION
**Pull request by Gautham-657**
Should not highlight green with negative exceptional items.

### CODE REVIEW

**Review by DEEJ4Y — COMMENTED** [review]
@Gautham-657 Why?

High other income is not a good sign. 
On the other hand, High other expenses are also not a good sign.

Any solutions?

**Comment by Gautham-657** [comment]
> @Gautham-657 Why?
> 
> High other income is not a good sign. On the other hand, High other expenses are also not a good sign.
> 
> Any solutions?

One of the solutions would be to notify with an "!" on the cell in which the other income and other cost has varied drastically.

**Comment by DEEJ4Y** [comment]
> One of the solutions would be to notify with an "!" on the cell in which the other income and other cost has varied drastically.

Okay, but how do we decide what is drastic. Some companies have other income increasing with the increase in revenue. Many cases there is no clear pattern of Exceptional Items. What would be a good way to decide what is drastic?

**Comment by Gautham-657** [comment]
> > One of the solutions would be to notify with an "!" on the cell in which the other income and other cost has varied drastically.
> 
> Okay, but how do we decide what is drastic. Some companies have other income increasing with the increase in revenue. Many cases there is no clear pattern of Exceptional Items. What would be a good way to decide what is drastic?

We can't decide drastic because it's not one size fit all kind of thing, we just have to notify that there is a change so that it doesn't go unnoticed

**Comment by DEEJ4Y** [comment]
With the current code, we can highlight only when there's a change in one direction. 

To implement for both directions we will need to use a different approach. If you have the bandwidth, please complete this feature in another PR. 

For now I am leaving it as is, as there's no simple solution.

**Pull request closed without merging**
